update QEMUOSE and lspci enhanced

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -7,18 +7,32 @@ else
 MACHINE=pc-0.11 
 endif
 
+IMG_NAME = $(SRCROOT)/bos.img
 TESTDIRS=$(wildcard test*)
 
 # -redir tcp:4080::80
 # tells qemu to listen on port 4080 and to forward connections to bos's port 80.
 NET_OPT=-net user -net nic,model=i82559er -redir tcp:4080::80
+QEMU=qemu
+QEMUOSE=/usr/local/qemuose/bin/qemu
+ifneq ($(shell which $(QEMUOSE)),)
+ifeq ($(QDEBUG),1)
+ QEMUEXTRA=-debug-e100
+endif
+QEMU=$(QEMUOSE) $(QEMUEXTRA)
+endif
+
 all: run
 
 run:
+	@if [ "x$(IMG_NAME)" = "x" -o ! -f "$(IMG_NAME)" ]; then \
+		echo "$(IMG_NAME) is not found, please make it in advance" ; \
+		exit 1 ; \
+	fi 
 ifeq ($(KNAME),$(KNAME_CYGWIN))
-	qemu -fda "$(IMG_NAME)" $(NET_OPT)
+	$(QEMU) -fda "$(IMG_NAME)" $(NET_OPT)
 else
-	qemu-system-x86_64 -boot a -M $(MACHINE) -fda "$(IMG_NAME)" $(NET_OPT)
+	$(QEMU) -M $(MACHINE) -fda "$(IMG_NAME)" $(NET_OPT)
 endif
 
 check:
